railscafe/config/routes.rb
Rails.application.routes.draw do
  resources :pastries
  get 'beverages' => 'beverages#index'

  get 'beverages/new' => 'beverages#new'

  post 'beverages/' => 'beverages#create'

end

railscafe/app/models/beverage.rb
class Beverage < ActiveRecord::Base
end

railscafe/app/models/pastry.rb
class Pastry < ActiveRecord::Base
end

railscafe/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

railscafe/app/controllers/beverages_controller.rb
# beverages controller inherits app controller
class BeveragesController < ApplicationController
  def index
  	# loop through beverage class
    @beverages = Beverage.all 
  end

  def new
  	# make new and create at the same time
  	# creates new beverage
  	@beverage = Beverage.new
  end

  def create
  	# params is a strong parameter control per controller action which actions can be changed 
  	# binding this instance of beverage and setting it equal to the create method being performed on the beverage class and we are saying for this instance of beverage I am permitting the user to input these fields
  	@beverage = Beverage.create(params.require(:beverage).permit(:bev_type, :price, :quantity, :roast, :brew, :expiration_date))
  	# if the above process goes smoothly, save this instance of beverage and after you save it redirect to beverages_path - we got this from rake routes in the terminal and the prefix for #index
  	if @beverage.save
  		redirect_to beverages_path
  	else
  		# if the above is not successful rerender my "new form" (new view)
  		render 'new'
  	end
  end

end

railscafe/app/controllers/pastries_controller.rb
class PastriesController < ApplicationController
  before_action :set_pastry, only: [:show, :edit, :update, :destroy]

  # GET /pastries
  # GET /pastries.json
  # eg: instagram when you see all of your photos
  def index
    @pastries = Pastry.all
  end

  # GET /pastries/1
  # GET /pastries/1.json
  # eg: instagram when you click on a single photo
  def show
  end

  # GET /pastries/new
  # create a new instance of a pastry class 
  # new view would probably take form data
  def new
    @pastry = Pastry.new
  end

  # GET /pastries/1/edit
  # edit content
  def edit
  end

  # POST /pastries
  # POST /pastries.json
  # create instance in the database. create doesn't get it's own view 
  # take what was in the 'new' form and passing it to database
  def create
    @pastry = Pastry.new(pastry_params)

    respond_to do |format|
      if @pastry.save
        format.html { redirect_to @pastry, notice: 'Pastry was successfully created.' }
        format.json { render :show, status: :created, location: @pastry }
      else
        format.html { render :new }
        format.json { render json: @pastry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pastries/1
  # PATCH/PUT /pastries/1.json
  # doesn't get it's own view
  # change what's in the database from the user edit of form
  def update
    respond_to do |format|
      if @pastry.update(pastry_params)
        format.html { redirect_to @pastry, notice: 'Pastry was successfully updated.' }
        format.json { render :show, status: :ok, location: @pastry }
      else
        format.html { render :edit }
        format.json { render json: @pastry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pastries/1
  # DELETE /pastries/1.json
  # deletes that instance from the database
  def destroy
    @pastry.destroy
    respond_to do |format|
      format.html { redirect_to pastries_url, notice: 'Pastry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # protect controller actions from outsiders from manipulating it
    def set_pastry
      @pastry = Pastry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pastry_params
      params.require(:pastry).permit(:name, :price, :quantity)
    end
end

railscafe/app/helpers/application_helper.rb
module ApplicationHelper
end

railscafe/app/helpers/beverages_helper.rb
module BeveragesHelper
end

railscafe/app/helpers/pastries_helper.rb
module PastriesHelper
end

railscafe/app/views/beverages/index.html.erb
<h1>Beverage List</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Roast</th>
      <th>Expiration Date</th>
      <th>Brew</th>
      <!-- column span is 6 because we have 6 indexes -->
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
  <!-- erb- embedded ruby -->
  <!-- looping through  -->
  <!-- do not use = at beginning for this -->
    <% @beverages.each do |beverage| %>
      <tr>
      <!-- like ng-repeat - every pastry in pastries show name, price, quantities -->
        <td><%= beverage.bev_type %></td>
        <td><%= beverage.price %></td>
        <td><%= beverage.quantity %></td>
        <td><%= beverage.roast %></td>
        <td><%= beverage.expiration_date %></td>
        <td><%= beverage.brew %></td>
      </tr>
    <% end %>
  </tbody>
</table>

railscafe/app/views/beverages/new.html.erb
<h1>Add a Beverage!</h1>

<!-- starting loop with do and use f as variable for form inputs -->
<%= form_for @beverage do |f| %>
<!-- Type: will appear on the form - specify data type on f. with text_field and adding the characteristic-->
  Type: <%= f.text_field :bev_type %>
  <!-- can use number.field -->
  Price: <%= f.text_field :price%>
  Quantity: <%= f.text_field :quantity%>
  Roast: <%= f.text_field :roast%>
  Brew: <%= f.text_field :brew %>
  <!-- date_field for date inputs -->
  Expiration Date: <%= f.date_field :expiration_date %>
  <!-- make a button to submit -->
  <%= f.submit "Add this Beverage!" %>
<!-- end the loop no = sign -->
<% end %>

railscafe/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railscafe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

railscafe/app/views/pastries/_form.html.erb
<%= form_for(@pastry) do |f| %>
  <% if @pastry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pastry.errors.count, "error") %> prohibited this pastry from being saved:</h2>

      <ul>
      <% @pastry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railscafe/app/views/pastries/edit.html.erb
<h1>Editing pastry</h1>

<%= render 'form' %>

<%= link_to 'Show', @pastry %> |
<%= link_to 'Back', pastries_path %>

railscafe/app/views/pastries/index.html.erb
<h1>Listing pastries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <!-- erb- embedded ruby -->
  <!-- looping through  -->
    <% @pastries.each do |pastry| %>
      <tr>
      <!-- like ng-repeat - every pastry in pastries show name, price, quantities -->
        <td><%= pastry.name %></td>
        <td><%= pastry.price %></td>
        <td><%= pastry.quantity %></td>
        <td><%= link_to 'Show', pastry %></td>
        <!-- rails helper method -->
        <!-- link me to edit follow edit path and send me to it's edit view -->
        <td><%= link_to 'Edit', edit_pastry_path(pastry) %></td>
        <td><%= link_to 'Destroy', pastry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pastry', new_pastry_path %>

railscafe/app/views/pastries/new.html.erb
<h1>New pastry</h1>

<%= render 'form' %>

<%= link_to 'Back', pastries_path %>

railscafe/app/views/pastries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pastry.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pastry.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @pastry.quantity %>
</p>

<%= link_to 'Edit', edit_pastry_path(@pastry) %> |
<%= link_to 'Back', pastries_path %>